/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'portfolio' : IDL.Null,
  'editorial' : IDL.Null,
  'blog' : IDL.Null,
  'bold' : IDL.Null,
  'minimal' : IDL.Null,
  'landing' : IDL.Null,
  'ecommerce' : IDL.Null,
});
export const DesignStyle = IDL.Record({
  'id' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'getAllDesignStyles' : IDL.Func([], [IDL.Vec(DesignStyle)], ['query']),
  'getDesignStyleById' : IDL.Func([IDL.Text], [DesignStyle], ['query']),
  'getDesignStylesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(DesignStyle)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'portfolio' : IDL.Null,
    'editorial' : IDL.Null,
    'blog' : IDL.Null,
    'bold' : IDL.Null,
    'minimal' : IDL.Null,
    'landing' : IDL.Null,
    'ecommerce' : IDL.Null,
  });
  const DesignStyle = IDL.Record({
    'id' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'getAllDesignStyles' : IDL.Func([], [IDL.Vec(DesignStyle)], ['query']),
    'getDesignStyleById' : IDL.Func([IDL.Text], [DesignStyle], ['query']),
    'getDesignStylesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(DesignStyle)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };