/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DesignStyle {
    id: string;
    tagline: string;
    name: string;
    description: string;
    category: Category;
}
export enum Category {
    portfolio = "portfolio",
    editorial = "editorial",
    blog = "blog",
    bold = "bold",
    minimal = "minimal",
    landing = "landing",
    ecommerce = "ecommerce"
}
export interface backendInterface {
    getAllDesignStyles(): Promise<Array<DesignStyle>>;
    getDesignStyleById(id: string): Promise<DesignStyle>;
    getDesignStylesByCategory(cat: Category): Promise<Array<DesignStyle>>;
}
import type { Category as _Category, DesignStyle as _DesignStyle } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllDesignStyles(): Promise<Array<DesignStyle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDesignStyles();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDesignStyles();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesignStyleById(arg0: string): Promise<DesignStyle> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignStyleById(arg0);
                return from_candid_DesignStyle_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignStyleById(arg0);
            return from_candid_DesignStyle_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesignStylesByCategory(arg0: Category): Promise<Array<DesignStyle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignStylesByCategory(to_candid_Category_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignStylesByCategory(to_candid_Category_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_DesignStyle_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignStyle): DesignStyle {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tagline: string;
    name: string;
    description: string;
    category: _Category;
}): {
    id: string;
    tagline: string;
    name: string;
    description: string;
    category: Category;
} {
    return {
        id: value.id,
        tagline: value.tagline,
        name: value.name,
        description: value.description,
        category: from_candid_Category_n4(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portfolio: null;
} | {
    editorial: null;
} | {
    blog: null;
} | {
    bold: null;
} | {
    minimal: null;
} | {
    landing: null;
} | {
    ecommerce: null;
}): Category {
    return "portfolio" in value ? Category.portfolio : "editorial" in value ? Category.editorial : "blog" in value ? Category.blog : "bold" in value ? Category.bold : "minimal" in value ? Category.minimal : "landing" in value ? Category.landing : "ecommerce" in value ? Category.ecommerce : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DesignStyle>): Array<DesignStyle> {
    return value.map((x)=>from_candid_DesignStyle_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    portfolio: null;
} | {
    editorial: null;
} | {
    blog: null;
} | {
    bold: null;
} | {
    minimal: null;
} | {
    landing: null;
} | {
    ecommerce: null;
} {
    return value == Category.portfolio ? {
        portfolio: null
    } : value == Category.editorial ? {
        editorial: null
    } : value == Category.blog ? {
        blog: null
    } : value == Category.bold ? {
        bold: null
    } : value == Category.minimal ? {
        minimal: null
    } : value == Category.landing ? {
        landing: null
    } : value == Category.ecommerce ? {
        ecommerce: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
